services:
  s{X}admin:
    image: dpage/pgadmin4
    container_name: 68-s{X}-admin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - secure-net
    depends_on:
      - s{X}db