services:
  s2app:
    image: prawee/strapi
    container_name: 67-s2-app
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: s2db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1337:1337"
    networks:
      - secure-net
    depends_on:
      s2db:
        condition: service_healthy